rdf::ImageOperations Class Reference
#include <ImageOperations.h>
Public Member Functions
ImageOperations ()
ImageOperations (const ImageOperations &orig)
void SetImagesDistribution (std::vector< Estructura::Node > &, int, int)
virtual ~ImageOperations ()
Private Member Functions
void AssignTreeFlagsToImagesSet (std::vector< Estructura::Node > &, int, int, int)
Static Private Member Functions
static std::mt19937 InitRandomSeed ()
Static Private Attributes
static std::mt19937 mt_ = ImageOperations::InitRandomSeed()
Constructor & Destructor Documentation
ImageOperations::ImageOperations ()
                                 {
}
ImageOperations::ImageOperations (const ImageOperations & orig)
                                                            {
}
ImageOperations::~ImageOperations () [virtual]
                                  {
}
Member Function Documentation
void ImageOperations::AssignTreeFlagsToImagesSet (std::vector< Estructura::Node > & imagesSet, int percentageNum, int treeNum, int totalSize) [private]
References mt_.
Referenced by SetImagesDistribution().
 {
    int count = 0;
    int randomNum = 0;
    int treeFlag = 0;
    std::uniform_int_distribution<int> int_dist(0, totalSize - 1);
    while (count < percentageNum) {
      randomNum = int_dist(mt_);
      treeFlag = imagesSet[randomNum].treesAvailability[treeNum];
      if (treeFlag == 0){
        imagesSet[randomNum].treesAvailability[treeNum] = 1;
        count++;
      }
    }
  }
std::mt19937 ImageOperations::InitRandomSeed () [static], [private]
References mt_.
                                           {
    std::random_device rd;
    std::mt19937 mt(rd());
    return mt;
}
void ImageOperations::SetImagesDistribution (std::vector< Estructura::Node > & imagesSet, int percentage, int numTrees)
References AssignTreeFlagsToImagesSet().
 {
    int total = imagesSet.size();
    int percentageNum = (percentage / 100) * total;
    for (int i = 0; i < numTrees; i++) {
      AssignTreeFlagsToImagesSet(imagesSet, percentageNum, i, total);
    }
}
Member Data Documentation
std::mt19937 ImageOperations::mt_ = ImageOperations::InitRandomSeed() [static], [private]
Referenced by AssignTreeFlagsToImagesSet(), and InitRandomSeed().
The documentation for this class was generated from the following files:
ImageOperations.h
ImageOperations.cpp