QueueThread Class Reference
#include <QueueThread.h>
Public Member Functions
QueueThread ()
QueueThread (const QueueThread &orig)
virtual ~QueueThread ()
void run ()
void connect (std::vector< Estructura::Node > structure, rdf::Task task, std::priority_queue< rdf::Task > tasks, rdf::NodeResult &nodeResult)
Public Attributes
std::thread thread
std::mutex mtx
std::condition_variable cv
bool ready = false
std::vector< Estructura::Node > structure
rdf::Task task
std::priority_queue< rdf::Task > tasks
rdf::NodeResult nodeResult
Private Member Functions
void sync ()
Constructor & Destructor Documentation
QueueThread::QueueThread ()
                         {
}
QueueThread::QueueThread (const QueueThread & orig)
                                                {
}
QueueThread::~QueueThread () [virtual]
                          {
}
Member Function Documentation
void QueueThread::connect (std::vector< Estructura::Node > structure, rdf::Task task, std::priority_queue< rdf::Task > tasks, rdf::NodeResult & nodeResult)
References run(), structure, sync(), task, and tasks.
Referenced by Scheduler::checkQueues().
                                                             {
    QueueThread::structure = structure;
    QueueThread::task = task;
    QueueThread::tasks = tasks;;
    
    
    sync();
    run();
}
void QueueThread::run ()
References cv, rdf::Task::getFeatureMatrix(), rdf::bpc::NodeTrainee< T >::GetMatrix(), rdf::Task::getNode(), rdf::Task::getTree(), init(), mtx, nodeResult, ready, rdf::bpc::NodeTrainee< T >::SetNodeId(), rdf::bpc::NodeTrainee< T >::SetTreeId(), structure, task, and thread.
Referenced by connect().
                      {
    std::unique_lock<std::mutex> lck(mtx);
    
    
    rdf::bpc::NodeTrainee<rdf::bpc::Cell> _node;
    _node.SetTreeId(task.getTree());
    _node.SetNodeId(task.getNode());
    _node.GetMatrix().AddFeaturesMat(task.getFeatureMatrix());
    
    
    //while (1) {
    //lck.lock();
    while (!ready) {
        /*if (!tasks.empty()) {
            sync();
        }*/
        cv.wait(lck);
        //lck.lock();
    }
    ready = false;
    
    thread = std::thread(init, std::ref(structure), std::ref(
      task), std::ref(nodeResult));
    if (QueueThread::thread.joinable()) {
        //Scheduler scheduler;
        //scheduler.addThreadQueue(*this);
        QueueThread::thread.join();
    }
    //}
}
void QueueThread::sync () [private]
References cv, mtx, and ready.
Referenced by connect().
                       {
    std::unique_lock<std::mutex> lck(mtx);
    ready = true;
    lck.unlock();
    cv.notify_one();
}
Member Data Documentation
std::condition_variable QueueThread::cv
Referenced by run(), and sync().
std::mutex QueueThread::mtx
Referenced by run(), and sync().
rdf::NodeResult QueueThread::nodeResult
Referenced by run().
bool QueueThread::ready = false
Referenced by run(), and sync().
std::vector<Estructura::Node> QueueThread::structure
Referenced by connect(), and run().
rdf::Task QueueThread::task
Referenced by connect(), and run().
std::priority_queue<rdf::Task> QueueThread::tasks
Referenced by connect().
std::thread QueueThread::thread
Referenced by run().
The documentation for this class was generated from the following files:
QueueThread.h
QueueThread.cpp