rdf::Task Class Reference
#include <Task.h>
Public Member Functions
Task ()
Task (int _rank, int _tree, int _node, bool _status)
Task (const Task &orig)
virtual ~Task ()
void showTask ()
void reduce (Task &pTask1)
int getNode () const
void setNode (int _node)
int getRank () const
void setRank (int _rank)
bool isStatus () const
void setStatus (bool _status)
int getTree () const
void setTree (int _tree)
rdf::bpc::FeaturesMat getFeatureMatrix () const
void setFeatureMatrix (rdf::bpc::FeaturesMat _featureMatrix)
bool operator< (const Task &pTask) const
bool operator== (const Task &pTask) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
int _rank
int _tree
int _node
bool _status
rdf::bpc::FeaturesMat _featureMatrix
Friends
class boost::serialization::access
Detailed Description
This class encapsulate a task in the process of training trees
Constructor & Destructor Documentation
rdf::Task::Task ()
References _featureMatrix, rdf::bpc::FeaturesMat::GenerateVectors(), rdf::bpc::FeaturesMat::SetFeaturesNumRange(), rdf::bpc::FeaturesMat::SetMatrixSize(), rdf::bpc::FeaturesMat::SetThresholdsNumRange(), THRESHOLD_AMOUNT, and VECTOR_AMOUNT.
              {
    _featureMatrix.SetMatrixSize(VECTOR_AMOUNT,
      THRESHOLD_AMOUNT);
    _featureMatrix.SetThresholdsNumRange(100,0);
    _featureMatrix.SetFeaturesNumRange(100,0);
    _featureMatrix.GenerateVectors();
    //_featureMatrix.Print();
}
rdf::Task::Task (int _rank, int _tree, int _node, bool _status)
References _node, _rank, _status, and _tree.
                                                              {
    _rank = _rank;
    _tree = _tree;
    _node = _node;
    _status = _status;
}
rdf::Task::Task (const Task & orig)
References _featureMatrix, _node, _rank, _status, and _tree.
                              {
    _rank = orig._rank;
    _tree = orig._tree;
    _node = orig._node;
    _status = orig._status;
    _featureMatrix = orig._featureMatrix;
}
rdf::Task::~Task () [virtual]
               {
    
}
Member Function Documentation
rdf::bpc::FeaturesMat rdf::Task::getFeatureMatrix () const [inline]
References _featureMatrix.
Referenced by init(), rdf::NodeResult::reduce(), and QueueThread::run().
                                                       {
                return _featureMatrix;
            }
int rdf::Task::getNode () const [inline]
References _node.
Referenced by rdf::ForestManager::addResuld(), init(), reduce(), QueueThread::run(), and rdf::DistributionManager::transferNodes().
                                {
                return _node;
            }
int rdf::Task::getRank () const [inline]
References _rank.
Referenced by rdf::ForestManager::addResuld(), init(), reduce(), and rdf::DistributionManager::transferNodes().
                                {
                return _rank;
            }
int rdf::Task::getTree () const [inline]
References _tree.
Referenced by rdf::ForestManager::addResuld(), init(), reduce(), QueueThread::run(), and rdf::DistributionManager::transferNodes().
                                {
                return _tree;
            }
bool rdf::Task::isStatus () const [inline]
References _status.
Referenced by rdf::ForestManager::addResuld(), reduce(), and rdf::DistributionManager::transferNodes().
                                  {
                return _status;
            }
bool rdf::Task::operator< (const Task & pTask) const [inline]
References _rank.
            {
                if(pTask._rank < this->_rank)
                    return true;
            }
bool rdf::Task::operator== (const Task & pTask) const [inline]
References _node, and _tree.
            {
                if(pTask._node == this->_node && pTask._tree == this->_tree)
                    return true;
            }
void rdf::Task::reduce (Task & pTask1)
References _node, _rank, _status, _tree, getNode(), getRank(), getTree(), and isStatus().
                                {
    _rank = _rank + pTask.getRank();
    _tree = _tree + pTask.getTree();
    _node = _node + pTask.getNode();
    _status = pTask.isStatus();
}
template<class Archive > void rdf::Task::serialize (Archive & ar, const unsigned int version) [inline], [private]
References _featureMatrix, _node, _rank, _status, and _tree.
            {
                ar & _rank;
                ar & _tree;
                ar & _node;
                ar & _status;
                ar & _featureMatrix;
            }
void rdf::Task::setFeatureMatrix (rdf::bpc::FeaturesMat _featureMatrix) [inline]
References _featureMatrix.
                                                                    {
                this->_featureMatrix = _featureMatrix;
            }
void rdf::Task::setNode (int _node) [inline]
References _node.
Referenced by rdf::ForestManager::addResuld(), rdf::ForestManager::initializeForest(), and main().
                                    {
                this->_node = _node;
            }
void rdf::Task::setRank (int _rank) [inline]
References _rank.
Referenced by rdf::ForestManager::addResuld(), rdf::ForestManager::initializeForest(), and main().
                                    {
                this->_rank = _rank;
            }
void rdf::Task::setStatus (bool _status) [inline]
References _status.
Referenced by rdf::ForestManager::addResuld(), rdf::ForestManager::initializeForest(), and main().
                                         {
                this->_status = _status;
            }
void rdf::Task::setTree (int _tree) [inline]
References _tree.
Referenced by rdf::ForestManager::addResuld(), rdf::ForestManager::initializeForest(), and main().
                                    {
                this->_tree = _tree;
            }
void rdf::Task::showTask ()
References _node, _rank, _status, and _tree.
Referenced by Scheduler::checkQueues(), rdf::NodeResult::reduce(), rdf::TrainManager::sendingResults(), rdf::ForestManager::showQueue(), and rdf::DistributionManager::waitingResults().
                       {
    std::cout << "{ " <<_rank << "," << _tree << "," << _node <<"," <<
      _status << " } \n";
}
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Member Data Documentation
rdf::bpc::FeaturesMat rdf::Task::_featureMatrix [private]
Feature Matrix
Referenced by getFeatureMatrix(), serialize(), setFeatureMatrix(), and Task().
int rdf::Task::_node [private]
Node Number
Referenced by getNode(), operator==(), reduce(), serialize(), setNode(), showTask(), and Task().
int rdf::Task::_rank [private]
Number of process
Referenced by getRank(), operator<(), reduce(), serialize(), setRank(), showTask(), and Task().
bool rdf::Task::_status [private]
Number of process
Referenced by isStatus(), reduce(), serialize(), setStatus(), showTask(), and Task().
int rdf::Task::_tree [private]
Tree Number
Referenced by getTree(), operator==(), reduce(), serialize(), setTree(), showTask(), and Task().
The documentation for this class was generated from the following files:
Task.h
Task.cpp