rdf::ForestManager Class Reference
#include <ForestManager.h>
Public Member Functions
ForestManager ()
ForestManager (const ForestManager &orig)
virtual ~ForestManager ()
void initializeForest ()
void showQueue ()
Task & getNextTask ()
bool addResuld (rdf::NodeResult &pResult)
std::map< Task, rdf::NodeResult > getResultMap () const
void setResultMap (std::map< Task, rdf::NodeResult > _resultMap)
vector< Task > getMatrixSteps () const
void setMatrixSteps (vector< rdf::Task > _matrixSteps)
rdf::Task getResult () const
void setResult (rdf::Task _result)
vector< vector< rdf::NodeResult > > getResults () const
void setResults (vector< vector< rdf::NodeResult > > _results)
bool isStatus () const
void setStatus (bool _status)
Private Attributes
vector< rdf::Task > _matrixSteps
vector< vector< rdf::NodeResult > > _results
bool _status
Task _result
std::map< Task, rdf::NodeResult > _resultMap
Detailed Description
Thisclass allow manage train nodes, trees.
Constructor & Destructor Documentation
rdf::ForestManager::ForestManager ()
References _status.
                                {
    _status=false;
}
rdf::ForestManager::ForestManager (const ForestManager & orig)
                                                         {
}
rdf::ForestManager::~ForestManager () [virtual]
                                 {
}
Member Function Documentation
bool rdf::ForestManager::addResuld (rdf::NodeResult & pResult)
References _matrixSteps, _resultMap, rdf::Task::getNode(), rdf::Task::getRank(), rdf::NodeResult::getResultSize(), rdf::NodeResult::getTask(), rdf::Task::getTree(), rdf::Task::isStatus(), rdf::Task::setNode(), rdf::Task::setRank(), rdf::Task::setStatus(), and rdf::Task::setTree().
Referenced by rdf::DistributionManager::waitingResults().
                                                    {
    std::cout<<"REDUCE: " << pResult.getResultSize() << "\n";
    _resultMap.find(pResult.getTask())->second.reduce(pResult);
    //_result.reduce(pResult);
    //_result.showTask();
    
    Task leftChild;
    Task rightChild;
    
    
    leftChild.setRank(pResult.getTask().getRank());
    leftChild.setTree(pResult.getTask().getTree());
    leftChild.setNode(2 * pResult.getTask().getNode());
    leftChild.setStatus(pResult.getTask().isStatus());
    
    rightChild.setRank(pResult.getTask().getRank());
    rightChild.setTree(pResult.getTask().getTree());
    rightChild.setNode(2 * pResult.getTask().getNode()-1);
    rightChild.setStatus(pResult.getTask().isStatus());
    
    _matrixSteps.push_back(leftChild);
    _matrixSteps.push_back(rightChild);
    std::cout<< "Adding child nodes, size: "<<_matrixSteps.size()<<"\n";
    NodeResult result;
    
    _resultMap.insert(std::make_pair(leftChild,result));
    _resultMap.insert(std::make_pair(leftChild,result));
    
    //leftChild.showTask();
    //rightChild.showTask();
    
    
    
    return true;
}
vector<Task> rdf::ForestManager::getMatrixSteps () const [inline]
                                                {
                return _matrixSteps;
            }
rdf::Task & rdf::ForestManager::getNextTask ()
References _matrixSteps.
                                        {
    std::cout << "Queue Size: " << _matrixSteps.size()<< "\n";
    rdf::Task &test = _matrixSteps[0];
    //_matrixSteps.erase(_matrixSteps.begin());
    return test;
}
rdf::Task rdf::ForestManager::getResult () const [inline]
                                      {
                return _result;
            }
std::map<Task, rdf::NodeResult> rdf::ForestManager::getResultMap () const [inline]
                                                             {
                return _resultMap;
            }
vector<vector<rdf::NodeResult> > rdf::ForestManager::getResults () const [inline]
                                                              {
                return _results;
            }
void rdf::ForestManager::initializeForest ()
References _matrixSteps, _resultMap, rdf::Task::setNode(), rdf::Task::setRank(), rdf::Task::setStatus(), rdf::Task::setTree(), and TREE_AMOUNT.
                                        {
    for(int i = 0; i < TREE_AMOUNT; i++){
        rdf::Task newTask;
        newTask.setRank(0);
        newTask.setTree(i);
        newTask.setNode(1);
        newTask.setStatus(false);
        _matrixSteps.push_back(newTask);
        rdf::NodeResult node;
        _resultMap.insert(std::make_pair(newTask,node));
    }
}
bool rdf::ForestManager::isStatus () const [inline]
                                  {
                return _status;
            }
void rdf::ForestManager::setMatrixSteps (vector< rdf::Task > _matrixSteps) [inline]
                                                              {
                this->_matrixSteps = _matrixSteps;
            }
void rdf::ForestManager::setResult (rdf::Task _result) [inline]
                                            {
                this->_result = _result;
            }
void rdf::ForestManager::setResultMap (std::map< Task, rdf::NodeResult > _resultMap) [inline]
                                                                      {
                this->_resultMap = _resultMap;
            }
void rdf::ForestManager::setResults (vector< vector< rdf::NodeResult > > _results) [inline]
                                                                     {
                this->_results = _results;
            }
void rdf::ForestManager::setStatus (bool _status) [inline]
                                         {
                this->_status = _status;
            }
void rdf::ForestManager::showQueue ()
References _matrixSteps, and rdf::Task::showTask().
Referenced by rdf::DistributionManager::waitingResults().
                                 {
    for(int i=0; i<_matrixSteps.size(); i++){
        rdf::Task temp = _matrixSteps[i];
        temp.showTask();
    }
}
Member Data Documentation
vector<rdf::Task> rdf::ForestManager::_matrixSteps [private]
Referenced by addResuld(), getNextTask(), initializeForest(), and showQueue().
Task rdf::ForestManager::_result [private]
std::map<Task,rdf::NodeResult> rdf::ForestManager::_resultMap [private]
Referenced by addResuld(), and initializeForest().
vector<vector<rdf::NodeResult> > rdf::ForestManager::_results [private]
bool rdf::ForestManager::_status [private]
Referenced by ForestManager().
The documentation for this class was generated from the following files:
ForestManager.h
ForestManager.cpp