rdf::ImageDispatcher Class Reference
#include <ImageDispatcher.h>
Public Member Functions
ImageDispatcher ()
ImageDispatcher (const ImageDispatcher &orig)
virtual ~ImageDispatcher ()
int analyzeResource (rdf::Resource &pResource)
void assignRanges (int pIntervals, bool pFlag)
void addResource (rdf::Resource &pResource)
void showRanges ()
std::vector< std::pair< int, int > > getImagesRanges () const
void setImagesRanges (std::vector< std::pair< int, int > > _imagesRanges)
Private Attributes
std::vector< std::pair< int, int > > _imagesRanges
std::vector< rdf::Resource > _resourceVector
Detailed Description
' This class identify resources from all different nodes and say how many images this node can load to the memory
Constructor & Destructor Documentation
rdf::ImageDispatcher::ImageDispatcher ()
                                    {
}
rdf::ImageDispatcher::ImageDispatcher (const ImageDispatcher & orig)
References _imagesRanges.
                                                               {
    _imagesRanges = orig._imagesRanges;
}
rdf::ImageDispatcher::~ImageDispatcher () [virtual]
{}
Member Function Documentation
void rdf::ImageDispatcher::addResource (rdf::Resource & pResource)
References _resourceVector.
Referenced by rdf::DistributionManager::transferResources().
                                                           {
    _resourceVector.push_back(pResource);
    
}
int rdf::ImageDispatcher::analyzeResource (rdf::Resource & pResource)
This function intents analyze resource from each nodes in order to determinate how many images can charge
Parameters
pResource : object that contains information about available memory in the node.
Returns
int : it is the number of images that can charge.
References rdf::Resource::getMemFree().
Referenced by assignRanges().
                                                              {
    // SOME KIND OF ANALYSIS OVER THE RESOURCE TO RETURN AN AMOUN NUMBER OF IMAGES
    
    int memAvaibale = pResource.getMemFree(); // KB
    int imageSize = 10000; // KB
    return memAvaibale / imageSize;
}
void rdf::ImageDispatcher::assignRanges (int pIntervals, bool pFlag)
This function assing the same number of images for each process and save them in a vector with a std::pair object
Parameters
pIntervals : how many process or intervals.
References _imagesRanges, _resourceVector, analyzeResource(), and TRAIN_IMAGES_AMOUNT.
Referenced by rdf::DistributionManager::transferResources().
                                                               {
    if(pFlag){
            int multiple = TRAIN_IMAGES_AMOUNT/pIntervals;
            for(int i = 0 ; i < TRAIN_IMAGES_AMOUNT; i++){
                if(i%multiple == 0){
                    int a = i;
                    int b = i + multiple-1;
                    std::pair<int,int> range(a,b);
                    _imagesRanges.push_back(range);
                }
            }
    }
    
    else {
        int imageSum = 0;
        for(int i = 0; i< _resourceVector.size(); i++){
            Resource temp = _resourceVector[i];
            
            if(i==0){
                int imageAmount = analyzeResource(temp);
                int a = i;
                int b = i + imageAmount - 1;
                imageSum = imageAmount + imageAmount;
                std::pair<int,int> range(a,b);
                _imagesRanges.push_back(range);
            }
            else {
                int imageAmount = analyzeResource(temp);
                std::pair<int,int> lastRange;
                lastRange = _imagesRanges.back();
                int a = lastRange.second+1;
                int b = lastRange.second + imageAmount-1;
                imageSum = imageAmount + imageAmount;
                std::pair<int,int> range(a,b);
                _imagesRanges.push_back(range);
                
            }
            
        }
    }
}
std::vector<std::pair<int, int> > rdf::ImageDispatcher::getImagesRanges () const [inline]
References _imagesRanges.
Referenced by rdf::DistributionManager::transferRanges().
                                                              {
            return _imagesRanges;
        }
void rdf::ImageDispatcher::setImagesRanges (std::vector< std::pair< int, int > > _imagesRanges) [inline]
References _imagesRanges.
                                                                          {
            this->_imagesRanges = _imagesRanges;
        }
void rdf::ImageDispatcher::showRanges ()
References _imagesRanges.
Referenced by rdf::DistributionManager::transferResources().
                                    {
    for(int i = 0 ; i < _imagesRanges.size(); i++){
        std::cout << "Node " << i+1 << ": [" <<_imagesRanges[i].first <<"," <<
      _imagesRanges[i].second << "] \n";
    }
}
Member Data Documentation
std::vector<std::pair<int,int> > rdf::ImageDispatcher::_imagesRanges [private]
Allow to save assigned image ranges
Referenced by assignRanges(), getImagesRanges(), ImageDispatcher(), setImagesRanges(), and showRanges().
std::vector<rdf::Resource> rdf::ImageDispatcher::_resourceVector [private]
Referenced by addResource(), and assignRanges().
The documentation for this class was generated from the following files:
ImageDispatcher.h
ImageDispatcher.cpp