ImageManager Class Reference
#include <ImageManager.h>
Public Member Functions
ImageManager ()
ImageManager (const ImageManager &orig)
virtual ~ImageManager ()
void showStructure (bool showImages)
void setRange (std::pair< int, int > pRange)
void loadImages ()
std::vector< Estructura::Node > getStructure () const
void setStructure (std::vector< Estructura::Node > structure)
Private Attributes
Image image
Estructura estructura
cv::Mat img
std::vector< Estructura::Node > structure
Estructura::DataMaster dataMaster
Constructor & Destructor Documentation
ImageManager::ImageManager ()
References dataMaster, Estructura::DataMaster::height, Estructura::DataMaster::node, Estructura::DataMaster::NumPoints, Estructura::DataMaster::NumTree, Estructura::DataMaster::tree, Estructura::DataMaster::type_Algorithm, and Estructura::DataMaster::width.
                           {
    dataMaster.NumPoints = 15;
    dataMaster.height = 240;
    dataMaster.width = 320;
    dataMaster.NumTree = 3;
    dataMaster.tree = 0;
    dataMaster.node = 0;
    dataMaster.type_Algorithm = "shotton";
}
ImageManager::ImageManager (const ImageManager & orig)
                                                   {
}
ImageManager::~ImageManager () [virtual]
                            {
}
Member Function Documentation
std::vector<Estructura::Node> ImageManager::getStructure () const [inline]
References structure.
                                                   {
        return structure;
    }
void ImageManager::loadImages ()
References dataMaster, Image::getStructura(), image, and structure.
Referenced by rdf::DistributionManager::transferRanges().
                              {
    image.getStructura(structure, dataMaster);
    
}
void ImageManager::setRange (std::pair< int, int > pRange)
References dataMaster, Estructura::DataMaster::endRead, and Estructura::DataMaster::startRead.
Referenced by rdf::DistributionManager::transferRanges().
                                                    {
    dataMaster.startRead = pRange.first;
    dataMaster.endRead = pRange.second;
}
void ImageManager::setStructure (std::vector< Estructura::Node > structure) [inline]
References structure.
                                                           {
        this->structure = structure;
    }
void ImageManager::showStructure (bool showImages)
References estructura, img, Estructura::seeImageDepth(), Estructura::seeImageLabel(), and structure.
                                                {
    //desmostracion de la estructura esta bien
    for (int i = 0; i < structure.size(); i++) {
        img = structure[i].imageLabel;
        std::vector<Estructura::Pixel> pixel = structure[i].points;
        if(showImages){
            estructura.seeImageLabel(img);
            estructura.seeImageDepth(240,320,img);
        }
        else {
            for (int j = 0; j < pixel.size(); j++) {
                std::cout << pixel[j].point<< "\n";
            }
        }
    }
}
Member Data Documentation
Estructura::DataMaster ImageManager::dataMaster [private]
Referenced by ImageManager(), loadImages(), and setRange().
Estructura ImageManager::estructura [private]
Referenced by showStructure().
Image ImageManager::image [private]
Referenced by loadImages().
cv::Mat ImageManager::img [private]
Referenced by showStructure().
std::vector<Estructura::Node> ImageManager::structure [private]
Referenced by getStructure(), loadImages(), setStructure(), and showStructure().
The documentation for this class was generated from the following files:
ImageManager.h
ImageManager.cpp