Collection Class Reference
#include <Collection.h>
Public Member Functions
Collection ()
Collection (const Collection &orig)
virtual ~Collection ()
void setImage (StrategyImage *TypeImage)
void readImage (int height, int width, std::string direction, cv::Mat &image)
Private Attributes
StrategyImage * stImage
Constructor & Destructor Documentation
Collection::Collection ()
                       {
}
Collection::Collection (const Collection & orig)
                                             {
}
Collection::~Collection () [virtual]
                        {
}
Member Function Documentation
void Collection::readImage (int height, int width, std::string direction, cv::Mat & image)
References StrategyImage::readImage(), and stImage.
Referenced by Image::generatedStructureShotton().
                                                                                  {
    cv::Mat imageTem;
    Collection::stImage->readImage(height,width,direction,imageTem);
    image = imageTem;
    
}
void Collection::setImage (StrategyImage * TypeImage)
References stImage.
Referenced by Image::generatedStructureShotton().
                                                 {
    Collection::stImage = TypeImage;
}
Member Data Documentation
StrategyImage* Collection::stImage [private]
Referenced by readImage(), and setImage().
The documentation for this class was generated from the following files:
Collection.h
Collection.cpp