rdf::bpc::Trainer Class Reference
#include <TrainerBPC.h>
Public Member Functions
Trainer ()
Trainer (const Trainer &orig)
void Train (Node *, std::vector< Estructura::Node > &, rdf::NodeResult &)
virtual ~Trainer ()
Constructor & Destructor Documentation
Trainer::Trainer ()
                 {
   
}
Trainer::Trainer (const Trainer & orig)
                                    {
}
Trainer::~Trainer () [virtual]
Reimplemented from rdf::Trainer.
                  {
}
Member Function Documentation
void Trainer::Train (Node * node, std::vector< Estructura::Node > & imagesTrainingSet, rdf::NodeResult & nodeResult) [virtual]
Implements rdf::Trainer.
References rdf::bpc::NodeTrainee< T >::GetMatrix(), rdf::bpc::NodeTrainee< T >::nodeId_, rdf::NodeResult::setMatrixResults(), and rdf::bpc::NodeTrainee< T >::treeId_.
Referenced by init().
                                                                                                       {
  std::cout<< "Trainning...\n";
  NodeTrainee<Cell>* nodeTrainee = static_cast<
      NodeTrainee<Cell>* > (node);
  int nodeId = nodeTrainee->nodeId_;
  int treeId = nodeTrainee->treeId_;
  int nodeInTree, pointsSize, treeFlag;
  std::vector<Estructura::Pixel> *points = nullptr;
  std::cout << "nodeId: "<< nodeId << "\ttreeId: "<< treeId << '\n';
  int n = 0;
  for (auto &image : imagesTrainingSet) { // for every image
    // treeFlag = image.treesAvailability[treeId];
     if (treeFlag == 0) continue; //this means image doesn't belong to given tree
      points = &image.points;
      for (auto const &point : *points) { // for every point
        // std::cout << "gg!" << ++n << '\n';
            nodeInTree = point.ubicacion[treeId];
            cv::Point p = point.point;
            
            /*if (nodeInTree == nodeId){
               // nodeTrainee->GetMatrix().EvaluatePointInMatrix(point); //for every feature and threshold
            }*/
          //std::cout << "Punto ("<< p.x << "," << p.y <<") \n";
        }
  }
// nodeTrainee->GetMatrix().Print();
   nodeResult.setMatrixResults(nodeTrainee->GetMatrix());
  //nodeResult.getMatrixResults().Print();
  
}
The documentation for this class was generated from the following files:
TrainerBPC.h
TrainerBPC.cpp