rdf::NodeResult Class Reference
#include <NodeResult.h>
Public Member Functions
NodeResult ()
NodeResult (const NodeResult &orig)
virtual ~NodeResult ()
void reduce (NodeResult &Result)
rdf::bpc::Matrix< rdf::bpc::Cell > getMatrixResults () const
void setMatrixResults (rdf::bpc::Matrix< rdf::bpc::Cell > _matrixResults)
Task getTask () const
void setTask (Task _task)
int getResultSize () const
void setResultSize (int _resultSize)
bool isStatus () const
void setStatus (bool _status)
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
int _resultSize = 0
bool _status
rdf::Task _task
rdf::bpc::Matrix< rdf::bpc::Cell > _matrixResults
Friends
class boost::serialization::access
Constructor & Destructor Documentation
rdf::NodeResult::NodeResult ()
                          {
}
rdf::NodeResult::NodeResult (const NodeResult & orig)
References _matrixResults, _resultSize, _status, and _task.
                                                {
    _resultSize = orig._resultSize;
    _status = orig._status;
    _task = orig._task;
    _matrixResults = orig._matrixResults;
}
rdf::NodeResult::~NodeResult () [virtual]
                           {
}
Member Function Documentation
rdf::bpc::Matrix<rdf::bpc::Cell> rdf::NodeResult::getMatrixResults () const [inline]
References _matrixResults.
Referenced by Scheduler::checkQueues().
                                                              {
                return _matrixResults;
            }
int rdf::NodeResult::getResultSize () const [inline]
References _resultSize.
Referenced by rdf::ForestManager::addResuld(), and reduce().
                                      {
                return _resultSize;
            }
Task rdf::NodeResult::getTask () const [inline]
References _task.
Referenced by rdf::ForestManager::addResuld(), Scheduler::checkQueues(), reduce(), rdf::TrainManager::sendingResults(), and rdf::DistributionManager::waitingResults().
                                 {
                return _task;
            }
bool rdf::NodeResult::isStatus () const [inline]
References _status.
Referenced by Scheduler::checkQueues().
                                  {
                return _status;
            }
void rdf::NodeResult::reduce (NodeResult & Result)
References _matrixResults, _resultSize, _status, rdf::bpc::Features::feature1_, rdf::bpc::Features::feature2_, rdf::Task::getFeatureMatrix(), rdf::bpc::FeaturesMat::GetFeaturesAt(), getResultSize(), getTask(), rdf::bpc::FeaturesMat::GetThresholdAt(), and rdf::Task::showTask().
                                              {
    std::cout << "reducing from ";
    pResult.getTask().showTask();
    _matrixResults.Reduce(pResult._matrixResults);
    
    std::cout << " \n Result left: " << _resultSize++ << "\n";
    if(_resultSize == pResult.getResultSize()){
        _status = true;
        std::cout << "ALL RESULTS from: ";
        pResult.getTask().showTask();
        std::pair<int,int> _featureIndex = pResult._matrixResults.FindBestPair();
        
        rdf::bpc::Features _feature = pResult.getTask().getFeatureMatrix().
      GetFeaturesAt(_featureIndex.first);
        float _threshold = pResult.getTask().getFeatureMatrix().GetThresholdAt(_featureIndex.second);
        
        std::cout << "FEATURES1: " << _feature.feature1_.x << "," << _feature.
      feature1_.y << "\n";
        std::cout << "FEATURES2: " << _feature.feature2_.x << "," << _feature.
      feature2_.y << "\n";
        std::cout << "THRESHOLS: " << _threshold << "\n";
    }
}
template<class Archive > void rdf::NodeResult::serialize (Archive & ar, const unsigned int version) [inline], [private]
References _matrixResults, _resultSize, _status, and _task.
            {
                ar & _resultSize;
                ar & _status;
                ar & _task;
                ar & _matrixResults;
            }
void rdf::NodeResult::setMatrixResults (rdf::bpc::Matrix< rdf::bpc::Cell > _matrixResults) [inline]
References _matrixResults.
Referenced by rdf::bpc::Trainer::Train().
                                                                           {
                this->_matrixResults = _matrixResults;
            }
void rdf::NodeResult::setResultSize (int _resultSize) [inline]
References _resultSize.
                                                {
                this->_resultSize = _resultSize;
            }
void rdf::NodeResult::setStatus (bool _status) [inline]
References _status.
Referenced by Scheduler::checkQueues().
                                         {
                this->_status = _status;
            }
void rdf::NodeResult::setTask (Task _task) [inline]
References _task.
Referenced by Scheduler::checkQueues(), and rdf::TrainManager::sendingResults().
                                     {
                this->_task = _task;
            }
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
This class allows to manage information about results of training
Member Data Documentation
rdf::bpc::Matrix<rdf::bpc::Cell> rdf::NodeResult::_matrixResults [private]
Referenced by getMatrixResults(), NodeResult(), reduce(), serialize(), and setMatrixResults().
int rdf::NodeResult::_resultSize = 0 [private]
To identify the number of results
Referenced by getResultSize(), NodeResult(), reduce(), serialize(), and setResultSize().
bool rdf::NodeResult::_status [private]
To know when all matix had been reduced
Referenced by isStatus(), NodeResult(), reduce(), serialize(), and setStatus().
rdf::Task rdf::NodeResult::_task [private]
To know which task produce the result
Referenced by getTask(), NodeResult(), serialize(), and setTask().
The documentation for this class was generated from the following files:
NodeResult.h
NodeResult.cpp