rdf::TrainManager Class Reference
#include <TrainManager.h>
Public Member Functions
TrainManager ()
TrainManager (const TrainManager &orig)
virtual ~TrainManager ()
bool validateConfiguration ()
bool initPlatform ()
void sendingNodes ()
void trainningNodes ()
void listeningResults ()
void sendingResults ()
Private Attributes
Initializator _initializator
rdf::DistributionManager _distributor
Constructor & Destructor Documentation
rdf::TrainManager::TrainManager ()
                              {
}
rdf::TrainManager::TrainManager (const TrainManager & orig)
                                                      {
}
rdf::TrainManager::~TrainManager () [virtual]
                               {
}
Member Function Documentation
bool rdf::TrainManager::initPlatform ()
References _distributor, rdf::DistributionManager::transferRanges(), and rdf::DistributionManager::transferResources().
                                   {
   // _manager.initializeForest();
    _distributor.transferResources();
    _distributor.transferRanges();
    return true;
}
void rdf::TrainManager::listeningResults ()
void rdf::TrainManager::sendingNodes ()
                                   {
    /*
    for(int i = 0; i < _manager.getMatrixSteps().size(); i++){
        //_manager.showQueue();
        rdf::Task tast = _manager.getMatrixSteps()[i];
        tast.showTask();
        _distributor.transferNodes(tast);
    }
    for(int i = 0; i < _manager.getMatrixSteps().size(); i++){
        //_manager.showQueue();
        rdf::Task tast = _manager.getMatrixSteps()[i];
        std::vector<std::string> _results;
        _results.push_back("hello");
        _results.push_back("world");
        rdf::NodeResult node;
        node.setTask(tast);
        _distributor.transferResults(node,_manager);
    }*/
 
}
void rdf::TrainManager::sendingResults ()
References rdf::NodeResult::getTask(), rdf::NodeResult::setTask(), and rdf::Task::showTask().
                                     {
    rdf::Task testTask = rdf::Task(1,1,0,0);
    rdf::NodeResult test;
    test.setTask(testTask);
    test.getTask().showTask();
}
void rdf::TrainManager::trainningNodes ()
bool rdf::TrainManager::validateConfiguration ()
References _initializator, and rdf::Initializator::createPlataform().
                                            {
   _initializator.createPlataform();
   return true;
}
Member Data Documentation
rdf::DistributionManager rdf::TrainManager::_distributor [private]
Referenced by initPlatform().
Initializator rdf::TrainManager::_initializator [private]
Referenced by validateConfiguration().
The documentation for this class was generated from the following files:
TrainManager.h
TrainManager.cpp