rdf::DistributionManager Class Reference
#include <DistributionManager.h>
Public Member Functions
DistributionManager ()
DistributionManager (const DistributionManager &orig)
virtual ~DistributionManager ()
void waitingResults ()
void sendingResults ()
void transferResources ()
void transferRanges ()
void transferNodes (Task &pTask)
void transferResults ()
void transferBeacon ()
void transferTrainStart (ForestManager &pForest)
void transferBestFeature (rdf::bpc::BestFeatureMsg pFeature)
void transferFinish ()
std::vector< std::pair< int, int > > getImageRanges () const
void setImageRanges (std::vector< std::pair< int, int > > _imageRanges)
ImageManager getMyImageManager () const
void setMyImageManager (ImageManager _myImageManager)
pair< int, int > getMyRange () const
void setMyRange (pair< int, int > _myRange)
Private Attributes
mpi::environment _env
mpi::communicator _world
std::vector< std::pair< int, int > > _imageRanges
pair< int, int > _myRange
ImageManager _myImageManager
rdf::ForestManager _forestManager
rdf::ImageDispatcher _imageDistpatcher
Scheduler _scheduler
Detailed Description
Class that works on distribute all messages within MPI.BOOST
Constructor & Destructor Documentation
rdf::DistributionManager::DistributionManager ()
{}
rdf::DistributionManager::DistributionManager (const DistributionManager & orig)
References _imageRanges, _myImageManager, and _myRange.
                                                                           {
    _imageRanges = orig._imageRanges;
    _myImageManager = orig._myImageManager;
    _myRange = orig._myRange;
}
rdf::DistributionManager::~DistributionManager () [virtual]
{}
Member Function Documentation
std::vector<std::pair<int, int> > rdf::DistributionManager::getImageRanges () const [inline]
GETTERS AND SETTERS FOR MAIN VARIABLES
References _imageRanges.
                                                             {
            return _imageRanges;
        }
ImageManager rdf::DistributionManager::getMyImageManager () const [inline]
References _myImageManager.
                                               {
            return _myImageManager;
        }
pair<int, int> rdf::DistributionManager::getMyRange () const [inline]
References _myRange.
                                          {
            return _myRange;
        }
void rdf::DistributionManager::sendingResults ()
References _scheduler, _world, and Scheduler::getResults().
Referenced by transferResults().
                                            {
    while(true){
        
        if(!_scheduler.getResults().empty()) {
            std::cout << "SENDING THREAD \n";
            _world.send(0, 2,_scheduler.getResults().front()) ;
            _scheduler.getResults().pop();
            
        }
    }
}
void rdf::DistributionManager::setImageRanges (std::vector< std::pair< int, int > > _imageRanges) [inline]
References _imageRanges.
                                                                        {
            this->_imageRanges = _imageRanges;
        }
void rdf::DistributionManager::setMyImageManager (ImageManager _myImageManager) [inline]
References _myImageManager.
                                                             {
            this->_myImageManager = _myImageManager;
        }
void rdf::DistributionManager::setMyRange (pair< int, int > _myRange) [inline]
References _myRange.
                                                 {
            this->_myRange = _myRange;
        }
void rdf::DistributionManager::transferBeacon ()
This messages is to ensure that all the process are running alive.
References _world.
                                            {
    if (_world.size() <= 1) {
    std::cout << "Need more than 1 processes to play around." << std::endl;
    }
    else {
        if(_world.rank() == 0){ // MASTER PROCESS
            std::string log = "logInfo";
            broadcast(_world, log, 0); // Send the task to every
       process in the cluster
            std::cout << "Master asking for log info log\n";
            std::string response;
            int i = 1;
            do { // Wait all the responses
                _world.recv(boost::mpi::any_source, boost::mpi::any_tag,response);
                std::cout << "Master Receive log information " << response << "\n";
                i++;
            }while(i<_world.size());
        }
        else {
            std::string logInfo;
            _world.recv(boost::mpi::any_source, boost::mpi::any_tag, logInfo);
            std::string response = "LOG_" + std::to_string(_world.rank());
            _world.send(0,0,response);
        }
    }
}
void rdf::DistributionManager::transferBestFeature (rdf::bpc::BestFeatureMsg pFeature)
This function allows to send the best feature in order to classify images.
Parameters
feature
vector1
vector2
References _world.
                                                                              {
     if (_world.size() <= 1) {
    std::cout << "Need more than 1 processes to play around." << std::endl;
    }
    else {
        if(_world.rank() == 0){
            rdf::bpc::BestFeatureMsg _bestFeature;
            broadcast(_world, _bestFeature, 0);
            std::cout << "Master is sending best feature\n";
        }
        else {
             rdf::bpc::BestFeatureMsg _bestFeature;
            _world.recv(boost::mpi::any_source, boost::mpi::any_tag, _bestFeature);
        }
    }
}
void rdf::DistributionManager::transferFinish ()
void rdf::DistributionManager::transferNodes (Task & pTask)
This function allows to send a Task that will be process by every cluster node.
Parameters
pTask // Task to process include (Rank,Tree, Node, Status, FeatureMatrix)
References _world, rdf::Task::getNode(), rdf::Task::getRank(), rdf::Task::getTree(), and rdf::Task::isStatus().
Referenced by main().
                                                      {
    if (_world.size() <= 1) {
    std::cout << "Need more than 1 processes to play around." << std::endl;
    }
    else {
        if(_world.rank() == 0){ // MASTER PROCESS
            broadcast(_world, pTask, 0); // Send the task to every
       process in the cluster
            std::cout << "Master Send (" << pTask.getRank() << "," << pTask.getTree() <<","
                    << pTask.getNode() << "," << pTask.isStatus()<< "] \n" ;
                        int i = 0;
                        std::string response;
                        do {
                            _world.recv(boost::mpi::any_source, boost::mpi::any_tag,response); //
       Ensure that slave receive the node
                            std::cout << "Master Received Confirmations " << response << "\n";
                            //_clusterResourses.push_back(response);
                            i++;
                        } while(i<_world.size()-1);
        }
        else { // SLAVE PROCESS
            Task toProcess; // Each slave receive the task;
            _world.recv(boost::mpi::any_source, boost::mpi::any_tag, toProcess);
            std::cout << "Process #" << _world.rank() << " node to process ("
            << toProcess.getRank() << "," << toProcess.getTree() << ","
            << toProcess.getNode() << "," << toProcess.isStatus()<< "] \n" ;
            std::string response = "OK_" + std::to_string(_world.rank()); // Confirmation Message for
       master node
            _world.send(0,0,response); // Send confirmation about
       received node
            //PROCESAR TAREA;
           // _scheduler.assingTask(_myImageManager.getStructure(),toProcess);
            
            int time = rand() % 1000000 + 10000;
            usleep(time);
        }
    }
}
void rdf::DistributionManager::transferRanges ()
This function send and receive messages about image ranges
References _imageDistpatcher, _myImageManager, _myRange, _world, rdf::ImageDispatcher::getImagesRanges(), ImageManager::loadImages(), and ImageManager::setRange().
Referenced by rdf::TrainManager::initPlatform(), and main().
                                            {
    if (_world.size() <= 1) {
        std::cout << "Need more than 1 processes to play around." << std::endl;
    }
    else {
        if(_world.rank()==0){ // MASTER PROCESS
            for(int i = 1; i<_world.size(); i++){
                _world.send(i,0,_imageDistpatcher.
      getImagesRanges().at(i-1)); // Send specific rank to each process.
            }
        }
        else{ // SLAVE PROCESS
          
            _world.recv(0, 0, _myRange); // Receive message
       from master
            std::cout << "Process #" << _world.rank() << " will work with [" <<
      _myRange.first << "," << _myRange.second<< "] \n" ;
            _myImageManager.setRange(_myRange); //
       Set range to imageManager
            const clock_t begin_time = clock();
            _myImageManager.loadImages();
            std::cout << "Time loading images Slave" << _world.rank() << " : " << float(clock () -
       begin_time) /double(CLOCKS_PER_SEC) << " seconds\n";
            //_myImageManager.showStructure(false); // Muestra el contenido de la
       estructura (0: pixeles, 1: C_Imagenes)
        }
    }
}
void rdf::DistributionManager::transferResources ()
This function send and receive messages about node resources
References _imageDistpatcher, _world, rdf::ImageDispatcher::addResource(), rdf::ImageDispatcher::assignRanges(), Resources::createObjet(), rdf::Resource::displayResource(), Resources::getResources(), and rdf::ImageDispatcher::showRanges().
Referenced by rdf::TrainManager::initPlatform(), and main().
                                               {
    
    if (_world.size() <= 1) {
        std::cout << "Need more than 1 processes to play around." << std::endl;
    }
    else {
        if(_world.rank() != 0){ // MASTER PROCESS
           // CREATING RESOURCES RESPONSE (WILL)
            Resources _resource;
            std::vector<std::string> _vector;
            _resource.getResources(_vector);
            rdf::Resource _node;
            _resource.createObjet(_vector,_node);
            _node.displayResource();
            _world.send(0,0,_node);
            std::cout << "Slave "<<_world.rank()<< " have send resources \n";
        }
        else { // SLAVE PROCESS
            Resource _nodeInfo;
            std::string response;
            int i = 1;
            do { // receive all responses all resourc
                _world.recv(boost::mpi::any_source, boost::mpi::any_tag,_nodeInfo);
                std::cout << "Master Received Resources \n";
                _nodeInfo.displayResource();
                _imageDistpatcher.addResource(_nodeInfo);
                //_clusterResourses.push_back(response);
                i++;
            }while(i<_world.size());
            _imageDistpatcher.assignRanges(_world.size()-1,false); //
       Assign ranges according with number of process.
            _imageDistpatcher.showRanges();
        }
    }
}
void rdf::DistributionManager::transferResults ()
This function allows to send the results to the master node.
Parameters
pResult
pForest
References _world, sendingResults(), and waitingResults().
                                             {
    if (_world.size() > 1) {
        if(_world.rank() != 0){
            std::thread t1(&rdf::DistributionManager::sendingResults
      , rdf::DistributionManager());
            t1.detach();
            
        }
        else{
            std::thread t2(&rdf::DistributionManager::waitingResults
      , rdf::DistributionManager());
            t2.detach();
        }
    }
    else {
        std::cout << "Need more than 1 processes to play around." << std::endl;
    }
}
void rdf::DistributionManager::transferTrainStart (ForestManager & pForest)
Parameters
pForest
References _world.
                                                                       {
    if (_world.size() <= 1) {
    std::cout << "Need more than 1 processes to play around." << std::endl;
    }
    else {
        //if(_world.rank() != 0){
            //START WILL PROCESS
            
        }
       // else{
            //ACTIVATE FLAG OR SHT
            
            
            
       // }
    //}
    
}
void rdf::DistributionManager::waitingResults ()
ALL THIS FUNCTIONS ARE FOR SENDING MESSAGES BETWEEN SLAVE NODES AND MASTER NODE All documentation about it is in DistributionManager.cpp
References _forestManager, _world, rdf::ForestManager::addResuld(), rdf::NodeResult::getTask(), rdf::ForestManager::showQueue(), and rdf::Task::showTask().
Referenced by transferResults().
                                            {
    while(true){
        std::cout << "WAITING THREAD \n";
        rdf::NodeResult newResult;
        _world.recv(boost::mpi::any_source, 2, newResult);
        newResult.getTask().showTask();
        _forestManager.addResuld(newResult);
        _forestManager.showQueue();
        
    }
}
Member Data Documentation
mpi::environment rdf::DistributionManager::_env [private]
Mpi variable to manage the enviroment
rdf::ForestManager rdf::DistributionManager::_forestManager [private]
Referenced by waitingResults().
rdf::ImageDispatcher rdf::DistributionManager::_imageDistpatcher [private]
Referenced by transferRanges(), and transferResources().
std::vector<std::pair<int,int> > rdf::DistributionManager::_imageRanges [private]
Vector that includes ranges for each process
Referenced by DistributionManager(), getImageRanges(), and setImageRanges().
ImageManager rdf::DistributionManager::_myImageManager [private]
It allows to get images from memory in the range
Referenced by DistributionManager(), getMyImageManager(), setMyImageManager(), and transferRanges().
pair<int,int> rdf::DistributionManager::_myRange [private]
Pair that allows ideantify the range by the process
Referenced by DistributionManager(), getMyRange(), setMyRange(), and transferRanges().
Scheduler rdf::DistributionManager::_scheduler [private]
Referenced by sendingResults().
mpi::communicator rdf::DistributionManager::_world [private]
Mpi variable to identify the world of process
Referenced by sendingResults(), transferBeacon(), transferBestFeature(), transferNodes(), transferRanges(), transferResources(), transferResults(), transferTrainStart(), and waitingResults().
The documentation for this class was generated from the following files:
DistributionManager.h
DistributionManager.cpp