rdf::bpc::FeaturesMat Class Reference
#include <FeaturesMat.h>
Public Member Functions
FeaturesMat ()
FeaturesMat (const FeaturesMat &orig)
FeaturesMat (int fn, float fh, float fl, int tn, float th, float tl)
void SetMatrixSize (int x, int y)
void SetNumThresholds (int)
void SetNumFeatures (int)
void SetThresholdsNumRange (float high, float low)
void SetFeaturesNumRange (float high, float low)
void GenerateVectors ()
void Print ()
virtual ~FeaturesMat ()
float GetThresholdAt (int x)
Features GetFeaturesAt (int x)
Private Member Functions
void GenerateThresholdsVector ()
void GenerateFeaturesVector ()
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::vector< float > thresholds_
std::vector< Features > features_
int numFeatures_
int numThresholds_
float thresholdsLowRange_
float thresholdsHighRange_
float featuresLowRange_
float featuresHighRange_
Static Private Attributes
static std::mt19937 mt_ = InitializeRandomDevice()
Friends
template<class T >
class Matrix
class boost::serialization::access
Constructor & Destructor Documentation
FeaturesMat::FeaturesMat ()
                         {
  thresholdsLowRange_ = 0;
  thresholdsHighRange_ = 0;
  featuresLowRange_ = 0;
  featuresHighRange_ = 0;
  numFeatures_ = 0;
  numThresholds_ = 0;
}
FeaturesMat::FeaturesMat (const FeaturesMat & orig)
References features_, numFeatures_, numThresholds_, and thresholds_.
                                                {
  SetMatrixSize(orig.numFeatures_, orig.numThresholds_);
  thresholds_ = orig.thresholds_;
  features_= orig.features_;
}
FeaturesMat::FeaturesMat (int fn, float fh, float fl, int tn, float th, float tl)
                                                                                         {
    SetMatrixSize(numFeatures, numThresholds);
    SetThresholdsNumRange(thresholdsHigh,thresholdsLow);
    SetFeaturesNumRange(featuresHigh, featuresLow);
}
FeaturesMat::~FeaturesMat () [virtual]
                          {
}
Member Function Documentation
void FeaturesMat::GenerateFeaturesVector () [private]
References rdf::bpc::Features::SetFeature1(), and rdf::bpc::Features::SetFeature2().
                                         {
    float randomFeature1X, randomFeature1Y, randomFeature2X, randomFeature2Y;
    Features myFeature;
    std::uniform_real_distribution<float> features_dist(featuresLowRange_,
      featuresHighRange_);
    for (size_t i = 0; i < numFeatures_; i++) {
        randomFeature1X = features_dist(mt_);
        randomFeature1Y = features_dist(mt_);
        randomFeature2X = features_dist(mt_);
        randomFeature2Y = features_dist(mt_);
        myFeature.SetFeature1(randomFeature1X, randomFeature1Y);
        myFeature.SetFeature2(randomFeature2X, randomFeature2Y);
        features_[i] = myFeature;
    }
}
void FeaturesMat::GenerateThresholdsVector () [private]
                                           {
    float randomThreshold;
    std::uniform_real_distribution<float> threshold_dist(thresholdsLowRange_,
      thresholdsHighRange_);
    for (size_t i = 0; i < numThresholds_; i++) {
        randomThreshold = threshold_dist(mt_);
        thresholds_[i] = randomThreshold;
    }
}
void FeaturesMat::GenerateVectors ()
Referenced by rdf::Task::Task().
                                  {
    GenerateThresholdsVector();
    GenerateFeaturesVector();
}
Features rdf::bpc::FeaturesMat::GetFeaturesAt (int x) [inline]
References features_.
Referenced by rdf::NodeResult::reduce().
                                          {
        return features_[x];
      }
float rdf::bpc::FeaturesMat::GetThresholdAt (int x) [inline]
References thresholds_.
Referenced by rdf::NodeResult::reduce().
                                        {
        return thresholds_[x];
      }
void FeaturesMat::Print ()
References rdf::bpc::Features::GetFeature1(), and rdf::bpc::Features::GetFeature2().
                        {
    float randomThreshold, randomFeature1X, randomFeature1Y, randomFeature2X, randomFeature2Y;
    Features feat;
    for (size_t i = 0; i < numFeatures_; i++) {
        feat = features_[i];
        randomFeature1X = feat.GetFeature1().x;
        randomFeature1Y = feat.GetFeature1().y;
        randomFeature2X = feat.GetFeature2().x;
        randomFeature2Y = feat.GetFeature2().y;
        for (size_t j = 0; j < numThresholds_; j++) {
            randomThreshold = thresholds_[j];
            cout << "[" << i << "][" << j << "]: T=" << randomThreshold
                    << "\tF1X=" << randomFeature1X << "\tF1Y=" << randomFeature1Y
                    << "\tF2X=" << randomFeature2X << "\tF2Y=" << randomFeature2Y << "\n";
        }
    }
}
template<class Archive > void rdf::bpc::FeaturesMat::serialize (Archive & ar, const unsigned int version) [inline], [private]
References features_, featuresHighRange_, featuresLowRange_, numFeatures_, numThresholds_, thresholds_, thresholdsHighRange_, and thresholdsLowRange_.
      {
        ar & thresholds_;
        ar & features_;
        ar & numFeatures_;
        ar & numThresholds_;
        ar & thresholdsLowRange_;
        ar & thresholdsHighRange_;
        ar & featuresLowRange_;
        ar & featuresHighRange_;
      }
void FeaturesMat::SetFeaturesNumRange (float high, float low)
Referenced by rdf::Task::Task().
                                                           {
    featuresLowRange_ = low;
    featuresHighRange_ = high;
}
void FeaturesMat::SetMatrixSize (int x, int y)
Referenced by rdf::Task::Task().
                                            {
    numFeatures_ = x; //Matrix ROWS
    numThresholds_ = y; //Matrix COLS
    features_.resize(x);
    thresholds_.resize(y);
}
void FeaturesMat::SetNumFeatures (int n)
                                      {
    numFeatures_ = n;
    features_.resize(n);
}
void FeaturesMat::SetNumThresholds (int n)
                                        {
    numThresholds_ = n;
    thresholds_.resize(n);
}
void FeaturesMat::SetThresholdsNumRange (float high, float low)
Referenced by rdf::Task::Task().
                                                             {
    thresholdsLowRange_ = low;
    thresholdsHighRange_ = high;
}
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
template<class T > friend class Matrix [friend]
Member Data Documentation
std::vector<Features> rdf::bpc::FeaturesMat::features_ [private]
Referenced by FeaturesMat(), GetFeaturesAt(), and serialize().
float rdf::bpc::FeaturesMat::featuresHighRange_ [private]
Referenced by serialize().
float rdf::bpc::FeaturesMat::featuresLowRange_ [private]
Referenced by serialize().
std::mt19937 FeaturesMat::mt_ = InitializeRandomDevice() [static], [private]
Referenced by InitializeRandomDevice().
int rdf::bpc::FeaturesMat::numFeatures_ [private]
Referenced by FeaturesMat(), and serialize().
int rdf::bpc::FeaturesMat::numThresholds_ [private]
Referenced by FeaturesMat(), and serialize().
std::vector<float> rdf::bpc::FeaturesMat::thresholds_ [private]
Referenced by FeaturesMat(), GetThresholdAt(), and serialize().
float rdf::bpc::FeaturesMat::thresholdsHighRange_ [private]
Referenced by serialize().
float rdf::bpc::FeaturesMat::thresholdsLowRange_ [private]
Referenced by serialize().
The documentation for this class was generated from the following files:
FeaturesMat.h
FeaturesMat.cpp