rdf::bpc::Cell Class Reference
#include <CellBPC.h>
Public Member Functions
Cell ()
Cell (const Cell &orig)
void Reduce (const Cell &other)
void SumByIndex (int toLeft, int index, float val)
void SumByBodyPart (int toLeft, std::string bodyPart, float val)
void InitValues (float leftVals, float rightVals)
void AverageValues (int num)
void Print ()
virtual ~Cell ()
Public Attributes
std::vector< float > left
std::vector< float > right
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
void Print (int i)
int BodyPartToIndex (std::string bodyPart)
Friends
class boost::serialization::access
Constructor & Destructor Documentation
rdf::bpc::Cell::Cell ()
References BODY_PARTS_NUM, left, and right.
               {
      left.resize(BODY_PARTS_NUM, 8.0);
      right.resize(BODY_PARTS_NUM, 1.0);
    }
rdf::bpc::Cell::Cell (const Cell & orig)
References left, and right.
                               {
      left = orig.left;
      right = orig.right;
    }
rdf::bpc::Cell::~Cell () [virtual]
Reimplemented from rdf::Cell.
                {
    }
Member Function Documentation
void rdf::bpc::Cell::AverageValues (int num)
References BODY_PARTS_NUM, left, and right.
                                   {
      for (int i = 0; i < BODY_PARTS_NUM; i++) {
        left[i] = left[i] / num;
        right[i] = right[i] / num;
      }
    }
int rdf::bpc::Cell::BodyPartToIndex (std::string bodyPart) [private]
Referenced by serialize(), and SumByBodyPart().
                                               {
      if (bodyPart == "brazo"){
        return 0;
      }
      else if (bodyPart == "dedo"){
        return 1;
      }
      else if (bodyPart == "mano"){
        return 2;
      }
      else if (bodyPart == "cabeza"){
        return 3;
      }
      else if (bodyPart == "pecho"){
        return 4;
      }
      /* etc..... */
    }
void rdf::bpc::Cell::InitValues (float leftVals, float rightVals)
References BODY_PARTS_NUM, left, and right.
                                                            {
      for (int i = 0; i < BODY_PARTS_NUM; i++) {
        left[i] = leftValues;
        right[i] = rightValues;
      }
    }
void rdf::bpc::Cell::Print ()
References BODY_PARTS_NUM, left, and right.
Referenced by serialize().
                    {
      for (int i = 0; i < BODY_PARTS_NUM; i++) {
        std::cout << "Left: " << left[i] << "\tRight: " << right[i] << std::endl;
      }
    }
void rdf::bpc::Cell::Print (int i) [private]
References left, and right.
                         {
        std::cout << "i[" << i << "]" <<"Left: " << left[i] << "\tRight: " <<
      right[i] << std::endl;
    }
void rdf::bpc::Cell::Reduce (const Cell & other)
References BODY_PARTS_NUM, left, and right.
                                       {
      float otherLeft, otherRight;
      for (int i = 0; i < BODY_PARTS_NUM; i++) {
        otherLeft = other.left[i];
        otherRight = other.right[i];
        left[i] = left[i] + otherLeft;
        right[i] = right[i] + otherRight;
      }
      // return *this;
    }
template<class Archive > void rdf::bpc::Cell::serialize (Archive & ar, const unsigned int version) [inline], [private]
References BodyPartToIndex(), left, Print(), and right.
          {
            ar & left;
            ar & right;
          }
void rdf::bpc::Cell::SumByBodyPart (int toLeft, std::string bodyPart, float val)
References BodyPartToIndex(), and SumByIndex().
                                                                     {
      int index = BodyPartToIndex(bodyPart);
      SumByIndex(toLeft, index, val);
    }
void rdf::bpc::Cell::SumByIndex (int toLeft, int index, float val)
References left, and right.
Referenced by SumByBodyPart().
                                                           {
      (toLeft) ? left[index] += value : right[index] += value;
    }
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Member Data Documentation
std::vector<float> rdf::bpc::Cell::left
Referenced by AverageValues(), Cell(), InitValues(), Print(), Reduce(), serialize(), and SumByIndex().
std::vector<float> rdf::bpc::Cell::right
Referenced by AverageValues(), Cell(), InitValues(), Print(), Reduce(), serialize(), and SumByIndex().
The documentation for this class was generated from the following files:
CellBPC.h
CellBPC.cpp