rdf::bpc::NodeTrainee< T > Class Template Reference
#include <NodeTraineeBPC.h>
Public Member Functions
NodeTrainee ()
NodeTrainee (const NodeTrainee &orig)
Matrix< T > & GetMatrix ()
virtual ~NodeTrainee ()
Node * GetLeft ()
Node * GetRight ()
int GetParentId ()
int GetLevel ()
void SetTreeId (int id)
void SetNodeId (int id)
Matrix< T > GetNodeMatrix ()
Public Attributes
int nodeId_
int treeId_
Private Attributes
Matrix< T > matrix_
Constructor & Destructor Documentation
template<typename T> rdf::bpc::NodeTrainee< T >::NodeTrainee ()
template<typename T> rdf::bpc::NodeTrainee< T >::NodeTrainee (const NodeTrainee< T > & orig)
template<typename T> virtual rdf::bpc::NodeTrainee< T >::~NodeTrainee () [virtual]
Reimplemented from rdf::NodeTrainee.
Referenced by rdf::bpc::NodeTrainee< T >::GetMatrix().
Member Function Documentation
template<typename T> Node* rdf::bpc::NodeTrainee< T >::GetLeft () [inline], [virtual]
Implements rdf::Node.
{};
template<typename T> int rdf::bpc::NodeTrainee< T >::GetLevel ()
Referenced by rdf::bpc::NodeTrainee< T >::GetParentId().
template<typename T> Matrix<T>& rdf::bpc::NodeTrainee< T >::GetMatrix () [inline]
References rdf::bpc::NodeTrainee< T >::matrix_, and rdf::bpc::NodeTrainee< T >::~NodeTrainee().
Referenced by init(), QueueThread::run(), and rdf::bpc::Trainer::Train().
{ return this->matrix_; };
template<typename T> Matrix<T> rdf::bpc::NodeTrainee< T >::GetNodeMatrix () [inline]
References rdf::bpc::NodeTrainee< T >::matrix_.
                                      {
        return matrix_;
      }
template<typename T> int rdf::bpc::NodeTrainee< T >::GetParentId () [inline]
References rdf::bpc::NodeTrainee< T >::GetLevel(), and rdf::bpc::NodeTrainee< T >::nodeId_.
{ return nodeId_ >> 1; }
template<typename T> Node* rdf::bpc::NodeTrainee< T >::GetRight () [inline], [virtual]
Implements rdf::Node.
{};
template<typename T> void rdf::bpc::NodeTrainee< T >::SetNodeId (int id) [inline]
References rdf::bpc::NodeTrainee< T >::nodeId_.
Referenced by init(), and QueueThread::run().
                                   {
        nodeId_ = id;
      }
template<typename T> void rdf::bpc::NodeTrainee< T >::SetTreeId (int id) [inline]
References rdf::bpc::NodeTrainee< T >::treeId_.
Referenced by init(), and QueueThread::run().
                                   {
        treeId_ = id;
      }
Member Data Documentation
template<typename T> Matrix<T> rdf::bpc::NodeTrainee< T >::matrix_ [private]
Referenced by rdf::bpc::NodeTrainee< T >::GetMatrix(), and rdf::bpc::NodeTrainee< T >::GetNodeMatrix().
template<typename T> int rdf::bpc::NodeTrainee< T >::nodeId_
Referenced by rdf::bpc::NodeTrainee< T >::GetParentId(), rdf::bpc::NodeTrainee< T >::SetNodeId(), and rdf::bpc::Trainer::Train().
template<typename T> int rdf::bpc::NodeTrainee< T >::treeId_
Referenced by rdf::bpc::NodeTrainee< T >::SetTreeId(), and rdf::bpc::Trainer::Train().
The documentation for this class was generated from the following file:
NodeTraineeBPC.h