QueueTask Class Reference
#include <QueueTask.h>
Classes
struct Queue
struct TaskStruct
Public Member Functions
QueueTask ()
QueueTask (const QueueTask &orig)
virtual ~QueueTask ()
void displayQueueTasks (struct Queue tasks)
void add (struct Queue &tasks, int rank, int tree, int node)
void isEmpty (struct Queue tasks, bool &empty)
void pop (struct Queue &tasks, struct TaskStruct &task)
void getNumberElements (struct Queue &tasks, int &numberElements)
Public Attributes
struct QueueTask::TaskStruct taskStruct
struct QueueTask::Queue queue
Private Member Functions
struct TaskStruct * createTask (int rank, int tree, int node)
void sortPriority (struct Queue &tasks)
void addQueue (struct Queue &tasks, int rank, int tree, int node)
Constructor & Destructor Documentation
QueueTask::QueueTask ()
                     {
}
QueueTask::QueueTask (const QueueTask & orig)
                                          {
}
QueueTask::~QueueTask () [virtual]
                      {
}
Member Function Documentation
void QueueTask::add (struct Queue & tasks, int rank, int tree, int node)
References addQueue(), and sortPriority().
                                                              {
    addQueue(tasks, rank, tree, node);
    sortPriority(tasks);
}
void QueueTask::addQueue (struct Queue & tasks, int rank, int tree, int node) [private]
References createTask(), QueueTask::Queue::first, QueueTask::Queue::last, and QueueTask::TaskStruct::next.
Referenced by add().
                                                                   {
    struct QueueTask::TaskStruct *aux = createTask(
      rank, tree, node);
    aux->next = 0;
    if (tasks.first == NULL) {
        tasks.first = aux;
    } else {
        tasks.last->next = aux;
    }
    tasks.last = aux;
}
struct QueueTask::TaskStruct * QueueTask::createTask (int rank, int tree, int node) [private]
References QueueTask::TaskStruct::node, QueueTask::TaskStruct::rank, and QueueTask::TaskStruct::tree.
Referenced by addQueue().
                                                                              {
    struct QueueTask::TaskStruct *newTask = new (struct
      QueueTask::TaskStruct);
    newTask->rank = rank;
    newTask->node = node;
    newTask->tree = tree;
    return newTask;
}
void QueueTask::displayQueueTasks (struct Queue tasks)
References QueueTask::Queue::first, QueueTask::TaskStruct::next, QueueTask::TaskStruct::node, QueueTask::TaskStruct::rank, and QueueTask::TaskStruct::tree.
                                             {
    struct QueueTask::TaskStruct *aux;
    aux = tasks.first;
    std::cout << "Las tareas son: " << "\n";
    std::cout << "****************" << "\n";
    while (aux != NULL) {
        std::cout << "Tree: " << aux->tree << " Node: " << aux->node << " Rank: " << aux->
      rank << std::endl;
        aux = aux->next;
    }
}
void QueueTask::getNumberElements (struct Queue & tasks, int & numberElements)
References QueueTask::Queue::first, and QueueTask::TaskStruct::next.
                                                                  {
    struct QueueTask::TaskStruct *aux;
    aux = tasks.first;
    numberElements = 0;
    while (aux != NULL) {
        aux = aux->next;
        numberElements +=1;
    }
}
void QueueTask::isEmpty (struct Queue tasks, bool & empty)
References QueueTask::Queue::first.
                                                {
    if (tasks.first == NULL) {
        empty = true;
    } else {
        empty = false;
    }
}
void QueueTask::pop (struct Queue & tasks, struct TaskStruct & task)
References QueueTask::Queue::first, and QueueTask::TaskStruct::next.
                                                                {
    struct QueueTask::TaskStruct *aux;
    aux = tasks.first;
    if (tasks.first != NULL) {
        tasks.first = aux->next;
        aux->next = NULL;
    } else {
        std::cout << "La lista esta vacia" << "\n";
    }
    task = *aux;
    delete aux;
}
void QueueTask::sortPriority (struct Queue & tasks) [private]
References QueueTask::Queue::first, QueueTask::TaskStruct::next, QueueTask::TaskStruct::node, QueueTask::TaskStruct::rank, and QueueTask::TaskStruct::tree.
Referenced by add().
                                         {
    struct QueueTask::TaskStruct *aux1, *aux2;
    int treeAux;
    int nodeAux;
    int rankAux;
    aux1 = tasks.first;
    while (aux1->next != NULL) {
        aux2 = aux1->next;
        while (aux2 != NULL) {
            if (aux1->tree >= aux2->tree) {
                if (aux1->node > aux2->node) {
                    treeAux = aux1->tree;
                    nodeAux = aux1->node;
                    rankAux = aux1->rank;
                    aux1->tree = aux2->tree;
                    aux1->node = aux2->node;
                    aux1->rank = aux2->rank;
                    aux2->tree = treeAux;
                    aux2->node = nodeAux;
                    aux2->rank = rankAux;
                }
            }
            aux2 = aux2->next;
        }
        aux1 = aux1->next;
    }
}
Member Data Documentation
struct QueueTask::Queue QueueTask::queue
struct QueueTask::TaskStruct QueueTask::taskStruct
The documentation for this class was generated from the following files:
QueueTask.h
QueueTask.cpp