Scheduler Class Reference
#include <Scheduler.h>
Public Member Functions
Scheduler ()
Scheduler (const Scheduler &orig)
virtual ~Scheduler ()
void assingTask (std::vector< Estructura::Node > structure, rdf::Task &task)
void addThreadQueue (QueueThread thread)
void start ()
void getResult (std::queue< rdf::NodeResult > &results)
void cleanQueueResult ()
std::queue< rdf::NodeResult > getResults () const
void setResults (std::queue< rdf::NodeResult > results)
Private Member Functions
void lock ()
void checkQueues (std::vector< Estructura::Node > structure, std::priority_queue< rdf::Task > tasks)
void sync ()
Private Attributes
std::queue< rdf::NodeResult > results
std::queue< QueueThread > threads
std::priority_queue< rdf::Task > tasks
std::vector< Estructura::Node > structureTemp
std::mutex mtx
std::condition_variable cv
bool ready = false
std::thread threadManager
Constructor & Destructor Documentation
Scheduler::Scheduler ()
References threads.
                     {
    for (int i = 0; i < 8; i++) {
        QueueThread thread;
        Scheduler::threads.push(thread);
    }
}
Scheduler::Scheduler (const Scheduler & orig)
                                          {
}
Scheduler::~Scheduler () [virtual]
                      {
}
Member Function Documentation
void Scheduler::addThreadQueue (QueueThread thread)
References threads.
Referenced by checkQueues().
                                                 {
    QueueThread threadTem;
    Scheduler::threads.push(thread);
}
void Scheduler::assingTask (std::vector< Estructura::Node > structure, rdf::Task & task)
References checkQueues(), and tasks.
                                                                             {
    //structureTemp = structure;
    tasks.push(task);
    checkQueues(structure, tasks);
}
void Scheduler::checkQueues (std::vector< Estructura::Node > structure, std::priority_queue< rdf::Task > tasks) [private]
References addThreadQueue(), QueueThread::connect(), rdf::NodeResult::getMatrixResults(), rdf::NodeResult::getTask(), rdf::NodeResult::isStatus(), lock(), ready, results, rdf::NodeResult::setStatus(), rdf::NodeResult::setTask(), rdf::Task::showTask(), sync(), tasks, threadManager, and threads.
Referenced by assingTask().
                                                                                                 {
    if (!tasks.empty()) {
        rdf::Task task = Scheduler::tasks.top();
        Scheduler::tasks.pop();
        sync();
        if (ready && threads.size() > 0) {
            //objeto node result
            rdf::NodeResult *nodeResult = new rdf::NodeResult();
            //rdf::NodeResult nodeResultTemp;
            nodeResult->setTask(task);
            QueueThread thread = Scheduler::threads.front();
            Scheduler::threads.pop();
            threadManager = std::thread(&QueueThread::connect,
      QueueThread(), structure, task, tasks, std::ref(*nodeResult));
            if (threadManager.joinable())
                threadManager.join();
            ready = false;
            addThreadQueue(thread);
            std::cout << "Task: ";
            nodeResult->getTask().showTask();
            std::cout << "Results: \n";
            nodeResult->getMatrixResults().Print();
            nodeResult->setStatus(0);
            //nodeResult.setMatrixResults(nodeResultTemp.getMatrixResults());
            results.push(*nodeResult);
            
            std::cout << results.size() << " \n";
            for (int i = 0; i < results.size(); i++) {
                 rdf::NodeResult nodetemp = results.front();
                 results.pop();
                 nodetemp.getTask().showTask();
                 
                 std::cout << "
      _______________________________________________________________________________ \n ";
                 nodetemp.getMatrixResults().Print();
                 std::cout << "CE: " << nodetemp.isStatus() << "\n";
                 std::cout << "
      ______________________________****************__________________________________\n ";
            }
            //nodeResult.getMatrixResults().Print();
            //results.push(nodeResult);
        } else {
            lock();
        }
    } else {
        if (threads.size() != 0) {
        }
    }
}
void Scheduler::cleanQueueResult ()
References results.
                                {
    for (int i = 0; i < results.size(); i++) {
        results.pop();
    }
}
void Scheduler::getResult (std::queue< rdf::NodeResult > & results)
References results.
                                                         {
    results = Scheduler::results;
}
std::queue<rdf::NodeResult> Scheduler::getResults () const [inline]
References results.
Referenced by rdf::DistributionManager::sendingResults().
                                               {
        return results;
    }
void Scheduler::lock () [private]
References cv, mtx, and ready.
Referenced by checkQueues().
                     {
    std::unique_lock<std::mutex> lck(mtx);
    while (!ready) {
        cv.wait(lck);
    }
}
void Scheduler::setResults (std::queue< rdf::NodeResult > results) [inline]
References results.
                                                     {
        this->results = results;
    }
void Scheduler::start ()
                      {
    //threadManager = std::thread(&Scheduler::checkQueues, this, structureTemp, tasks);
    //rdf::Task task;
    //threadManager = std::thread(&QueueThread::connect,QueueThread(), structureTemp, task, tasks);
}
void Scheduler::sync () [private]
References cv, mtx, and ready.
Referenced by checkQueues().
                     {
    std::unique_lock<std::mutex> lck(mtx);
    ready = true;
    cv.notify_one();
}
Member Data Documentation
std::condition_variable Scheduler::cv [private]
Referenced by lock(), and sync().
std::mutex Scheduler::mtx [private]
Referenced by lock(), and sync().
bool Scheduler::ready = false [private]
Referenced by checkQueues(), lock(), and sync().
std::queue<rdf::NodeResult> Scheduler::results [private]
Referenced by checkQueues(), cleanQueueResult(), getResult(), getResults(), and setResults().
std::vector<Estructura::Node> Scheduler::structureTemp [private]
std::priority_queue<rdf::Task> Scheduler::tasks [private]
Referenced by assingTask(), and checkQueues().
std::thread Scheduler::threadManager [private]
Referenced by checkQueues().
std::queue<QueueThread> Scheduler::threads [private]
Referenced by addThreadQueue(), checkQueues(), and Scheduler().
The documentation for this class was generated from the following files:
Scheduler.h
Scheduler.cpp