PointsSelect Class Reference
#include <PointsSelect.h>
Public Member Functions
PointsSelect ()
PointsSelect (const PointsSelect &orig)
virtual ~PointsSelect ()
void generatedPoints (std::string type_Algorithm, std::vector< Estructura::Pixel > &points, int NumPoints, int height, int width, int NumTree)
Private Member Functions
void generatShoton (std::vector< Estructura::Pixel > &points, int NumPoints, int height, int width, int NumTree)
Constructor & Destructor Documentation
PointsSelect::PointsSelect ()
                           {
}
PointsSelect::PointsSelect (const PointsSelect & orig)
                                                   {
}
PointsSelect::~PointsSelect () [virtual]
                            {
}
Member Function Documentation
void PointsSelect::generatedPoints (std::string type_Algorithm, std::vector< Estructura::Pixel > & points, int NumPoints, int height, int width, int NumTree)
References generatShoton().
Referenced by Image::generatedStructureShotton().
                                                                                                           
                                            {
    
    std::vector<Estructura::Pixel> temporal;
    if(type_Algorithm.compare(0,7,"shotton") == 0){
        generatShoton(temporal, NumPoints, height, width, NumTree);
        
    }
    points = temporal;
}
void PointsSelect::generatShoton (std::vector< Estructura::Pixel > & points, int NumPoints, int height, int width, int NumTree) [private]
References Estructura::Pixel::point, and Estructura::Pixel::ubicacion.
Referenced by generatedPoints().
                                                                                                           
                {
    
    
    std::vector<int> start (NumTree,0);
    Estructura::Pixel pixelTemp;
    
    for (int i = 0; i < NumPoints; i++) {
        pixelTemp.point = cv::Point((rand() % (height - 0)),((rand() % (width - 0))));
        pixelTemp.ubicacion = start;
        points.push_back(pixelTemp);
    }
}
The documentation for this class was generated from the following files:
PointsSelect.h
PointsSelect.cpp