QueueThread.cpp File Reference
#include <exception>
*
#include `QueueThread.h`
*
#include `Scheduler.h`
*
#include `NodeTraineeBPC.h`
*
#include `TrainerBPC.h`
*
Functions
void init (std::vector< Estructura::Node > &structure, rdf::Task &task, rdf::NodeResult &nodeResult)
Function Documentation
void init (std::vector< Estructura::Node > & structure, rdf::Task & task, rdf::NodeResult & nodeResult)
References rdf::Task::getFeatureMatrix(), rdf::bpc::NodeTrainee< T >::GetMatrix(), rdf::Task::getNode(), rdf::Task::getRank(), rdf::Task::getTree(), rdf::bpc::NodeTrainee< T >::SetNodeId(), rdf::bpc::NodeTrainee< T >::SetTreeId(), and rdf::bpc::Trainer::Train().
Referenced by QueueThread::run().
                                                                                           {
    std::cout << "********************************************** SLAVE " << task.
      getRank() << " is TRAINNING *************************************\n";
    rdf::bpc::NodeTrainee<rdf::bpc::Cell> _node;
    rdf::NodeResult *nodeResultTemp = new rdf::NodeResult();
    _node.SetTreeId(task.getTree());
    _node.SetNodeId(task.getNode());
    _node.GetMatrix().AddFeaturesMat(task.getFeatureMatrix());
    //std::cout << "SIZE " << structure.size() <<"\n";
    
    cv::Mat img = structure[0].imageLabel;
    
    
    rdf::bpc::Trainer trainer;
    trainer.Train(&_node,structure, nodeResult); // cambiar para meter nodeResult
    
// nodeResult = nodeResultTemp;
    //std::cout << " SIZE " << img<< "\n";
    
}